apiVersion: v1
kind: Service
metadata:
  name: vote-app-service
  labels:
    app: vote-app
spec:
  selector:
    app: vote-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
  type: NodePort 