apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/JNSalvatierra/challenge-manifests.git'
    targetRevision: main
    path: vote
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
